version: '3.9'

services:
  database:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"

  backend:
    build: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8000:8000"

  frontend:
    build: frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:3000"
